### PR TITLE
Change some default icons

### PR DESCRIPTION
**Pull request by Particpant**

### CODE REVIEW

**Review by t3chguy — APPROVED** [review]
Great, I ran out of energy last night before I got to the icons, much appreciated!

**Comment by Particpant** [comment]
Np! Thanks!
Any hope that this'll be ultimately able to control/issue commands to the pinecil? (set temp, mainly.)

**Comment by t3chguy** [comment]
Didn't even consider it but happy to look into it, the underlying pinecil library already supports it as it also empowers PineSAM so give me a few days and I'll give it a go

**Comment by t3chguy** [comment]
@Particpant give the latest a go, the Set Temperature is now settable

image

Will look into some other settable numbers shortly, as well as tweaking the device info attributes and tidying the code. FRs welcome.

**Comment by Particpant** [comment]
nice, thanks! Seems to work, but I'm at my laptop just fiddling with a phone charger, not near a real power supply. Will report back when I have a moment to test for real.

**Comment by Particpant** [comment]
First time really using it yesterday, I was finding that the integration would tend not to come back from unavailable after waking the Pinecil from idle or unplugging it.

**Comment by Particpant** [comment]
When I have some more time I'll try to repro with debug logging enabled.

**Comment by Particpant** [comment]
I can't file an issue, since yours is still a "fork" of a toothbrush integration, but I think I have something useful in the logs... Seems like this code throws an exception when the pinecil disconnects:
```
2024-01-20 21:48:54.016 ERROR (MainThread) [root] A message handler raised an exception: 
Traceback (most recent call last):
  File "src/dbus_fast/message_bus.py", line 798, in dbus_fast.message_bus.BaseMessageBus._process_message
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/manager.py", line 998, in _parse_msg
    watcher.on_connected_changed(new_connected)
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 168, in on_connected_changed
    self._disconnected_callback()
  File "/usr/local/lib/python3.11/site-packages/pinecil/ble.py", line 48, in __on_disconnected
    raise DeviceDisconnectedException
pinecil.ble.DeviceDisconnectedException
```
Screenshot 2024-01-21 221116
Looks like it also fails setup if it doesn't see the Pinecil. I _think_ it should probably be just fine setting up until the pinecil becomes available again? That might be why it tends to not pick the thing back up when it comes back from sleep/power loss.

**Comment by t3chguy** [comment]
I'm fairly new to BLE in HA, do you have any examples of active BLE connection integrations which operate like this? I can only find examples of passive ones. My Pinecil doesn't drop BLE connection when it goes to sleep at all.

**Comment by Particpant** [comment]
I've not used a lot of BLE _in_ HA, but, for example, I've got a BLE device in the core https://www.home-assistant.io/integrations/xiaomi_ble xiaomi ble integration. When it's unpowered (no batteries) the integration keeps the last known values.

Similarly this HACS integration for extended data out of an Xiaomi scale keeps the last received values: https://github.com/dckiller51/bodymiscale when the device is offline.

I'd say the retaining previous data behavior isn't desirable for more than a minute or two, it's probably a safety issue to report stale data when the integration isn't getting new data (wouldn't want to falsely report it's idle or at low temp when the truth is the integration doesn't know!)- switching to unknown/unavailable is still the right move, but I'm thinking handling the DeviceDisconnectedException and setting the sensors to unavailable when it is raised should be good. I suspect leaving it unhandled is what is causing the integration to misbehave?

**Comment by t3chguy** [comment]
https://github.com/home-assistant/core/blob/dev/homeassistant/components/xiaomi_ble/device.py#L15
And the bodymiscale is also based on passive mode tracking though in a different way

We can't use Passive for the Pinecil unfortunately due to wanting the ability to write to it, could possibly split it up into two devices, one for the sensors and one with the outputs

**Comment by Particpant** [comment]
Ahh, gotcha! I don't have any devices that do behave like that but I'll see if I can find any.

**Comment by Particpant** [comment]
So, looking at the various BT docs, it seems like a different coordinator (instead of `DataUpdateCoordinator`) is in order.
From here: 
https://developers.home-assistant.io/docs/core/bluetooth/bluetooth_fetching_data?_highlight=ble#activebluetoothcoordinator
It looks like `ActiveBluetoothDataUpdateCoordinator` is the one to use, since from the pinecil library, the device requires polling. It looks like you'd want `mode=bluetooth.BluetoothScanningMode.ACTIVE,`
and `connectable=True,` set for this device.

Switchbot uses this one (though they wrap it):
https://github.com/home-assistant/core/blob/dev/homeassistant/components/switchbot/coordinator.py
Here's a non core integration using the ActiveBluetoothDataUpdateCoordinator (a BLE door lock):
https://github.com/tispokes/hass_nuki_bt/blob/9335f88f09863484b98bc5cffc7333ba0696cef0/custom_components/hass_nuki_bt/coordinator.py
A different electric toothbrush:
https://github.com/irakhlin/sonicare-integration/blob/3ebb7a831ccb361e42aa236237fd9429c3e37fee/custom_components/sonicare/__init__.py
And an air conditioner (looks like they started from the switchbot integration):
https://github.com/hunterjm/ac-infinity-hacs/blob/1655604bf8839634dba32df9f1ede7093e00fdf3/custom_components/ac_infinity/coordinator.py

**Comment by t3chguy** [comment]
@Particpant good hunting, will see what I can do with it. Have also requested an unforking for this repo so we can have issues.

**Comment by t3chguy** [comment]
@Particpant check out the `rewrite` branch - you'll likely need to delete your existing integrations but at least now it has autodiscovery.

image

ActiveBluetoothDataUpdateCoordinator does not seem to work quite as expected however, as it only polls when it sees another advertisement from the device, and the advertisements seem to stop once we are connected to it causing the data to only update once at the very start and never again later.

**Comment by t3chguy** [comment]
Looks like advertising stops due to the options which IronOS specifies

https://github.com/Ralim/IronOS/blob/6e2bca9699347d9d1381087149ab70ca0f6fcb4c/source/Core/BSP/Pinecilv2/ble_peripheral.c#L269-L270
https://docs.zephyrproject.org/apidoc/latest/group__bt__gap.html#gga77867ab4129f63159b37bca3b652a798a7d12782a02afefcf4b5c04442a99f8a2

**Comment by Particpant** [comment]
Oh... hmm. Yeah, it looks like the poll_needed is set up correctly. That's a surprise.
I'll have a chance to give this a shot over the weekend!

**Comment by t3chguy** [comment]
`needs_poll_method` is only called when an advertisement is received, which won't happen from the Pinecil due to how its configured - https://github.com/Ralim/IronOS/issues/1559 would be another way around it

**Comment by Particpant** [comment]
Oh, nice. If I have a chance I can see if there's anything in the docs that would enable triggering a poll without an advertisement. Otherwise, I think it's worth waiting for that other *issue* in the iron itself.

**Pull request merged**
